### ISSUE TITLE
prejmenovat unix advanced 1 a 2 na neco lepsiho

### ISSUE THREAD

**Issue by libor-m** [libor-m/ngs-course#15]
pripadne prehodit par bloku aby to vic davalo smysl

nahodile navrhy/smer
adv 1 -> regexp a kamaradi -> text processing

adv 2 -> project management (awk v nadpisu nebude?) (sem patri screen a organizace adresaru)

**Comment by vjanousk** [comment]
V project management by se hodilo i zminit git..
Znas tmux jako alternativa k screen??

**Comment by vjanousk** [comment]
Predelavam session, kterou jsem mel v nedeli odpoledne a budu tam zminovat git...

> V project management by se hodilo i zminit git..
> Znas tmux jako alternativa k screen??

**Comment by libor-m** [comment]
mno, uplne si nejsem jistej, jestli stihnu nejak predelat ten obsah .. takze mozna jeste zustane 'advanced' ;)
