### ISSUE TITLE
UNIX vs Unix

### ISSUE THREAD

**Issue by libor-m** [libor-m/ngs-course#27]
Vseobecny konsenzus po internetu se zda ze je UNIX jako trademark pro systemy pochazejici z Bell Labs, Unix/unix jako oznaceni typu systemu.

**Comment by libor-m** [comment]
nechal bych to ALL CAPS jen v nazvu kurzu

**Comment by vjanousk** [comment]
> nechal bych to ALL CAPS jen v nazvu kurzu

A pouzival bys Unix nebo unix??

**Comment by libor-m** [comment]
hromadne jsem to zmenil na Unix na webu
