### ISSUE TITLE
presunout `screen` do advanced 2

### ISSUE THREAD

**Issue by libor-m** [libor-m/ngs-course#9]
zminit to v ramci unix 'project management' session

**Comment by vjanousk** [comment]
tmux jako alternative ke screen?

**Comment by libor-m** [comment]
Myslím že jim rozhodně nechceme motat hlavu dvěma alternativami. Já
používám screen, takže ho znám líp. Je tmux nějak zásadně lepší v těch pár
funkcích co učíme?

**Comment by vjanousk** [comment]
Parkrat jsem to zkousel, podle reviews co jsem cetl, je pry tmux lepsi nez screen, ale priznam se ze nevim uplne presne v cem :). Jen navrh, klidne nechme screen ;).

**Comment by libor-m** [comment]
Ja se mam tendenci drzet spis safe defaults, nez fancy new toys .. cili
bash a screen vs tmux a zsh napriklad. To si pak power useri, ktere bavi
tim travit cas, muzou hodiny a dny konfigurovat sami;)

**Comment by libor-m** [comment]
screen budeme potrebovat od zacatku, kdyz to jede na realnem serveru

**Comment by libor-m** [comment]
zaviram, protoze screen pojedeme remote od zacatku
